/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartIndexRouteImport } from './routes/start/index'
import { Route as StartPropertyTypeRouteImport } from './routes/start.$propertyType'
import { Route as ResultsPresetIdRouteImport } from './routes/results/$presetId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartPropertyTypeRoute = StartPropertyTypeRouteImport.update({
  id: '/start/$propertyType',
  path: '/start/$propertyType',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsPresetIdRoute = ResultsPresetIdRouteImport.update({
  id: '/results/$presetId',
  path: '/results/$presetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/results/$presetId': typeof ResultsPresetIdRoute
  '/start/$propertyType': typeof StartPropertyTypeRoute
  '/start': typeof StartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/results/$presetId': typeof ResultsPresetIdRoute
  '/start/$propertyType': typeof StartPropertyTypeRoute
  '/start': typeof StartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/results/$presetId': typeof ResultsPresetIdRoute
  '/start/$propertyType': typeof StartPropertyTypeRoute
  '/start/': typeof StartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/results/$presetId'
    | '/start/$propertyType'
    | '/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/results/$presetId'
    | '/start/$propertyType'
    | '/start'
  id:
    | '__root__'
    | '/'
    | '/welcome'
    | '/results/$presetId'
    | '/start/$propertyType'
    | '/start/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  ResultsPresetIdRoute: typeof ResultsPresetIdRoute
  StartPropertyTypeRoute: typeof StartPropertyTypeRoute
  StartIndexRoute: typeof StartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/$propertyType': {
      id: '/start/$propertyType'
      path: '/start/$propertyType'
      fullPath: '/start/$propertyType'
      preLoaderRoute: typeof StartPropertyTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$presetId': {
      id: '/results/$presetId'
      path: '/results/$presetId'
      fullPath: '/results/$presetId'
      preLoaderRoute: typeof ResultsPresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  ResultsPresetIdRoute: ResultsPresetIdRoute,
  StartPropertyTypeRoute: StartPropertyTypeRoute,
  StartIndexRoute: StartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
